# This file defines global variables that are shared across all simulation types

hydra:
  run:
    dir: .  # Use current directory instead of creating outputs/ subdirectories
  
  job:
    chdir: false  # Don't change working directory

defaults:
  - _self_

# Global variables - these are generally not changed when working within directories
global:
  # System information and commonly adjusted system parameters. 
  force_field: "amber"
  water_model: "tip3p"
  hmass_repart: False 
  
  # Some of these parameters need to have consistency?
  target_temperature: 300.0
  tartgetpressure: 1.0
  nonbonded_cutoff: 10.0
  langevin_damping: 1.0

  # Umbrella sampling parameters and input files
  windows: 2
  input_files_dir: "./config" # 
  
  # Computational resources (for submission scripts and interactive jobs on HPC?)
  user: "CTMR"
  node: "rtx_2080" 
  cpus_per_node: 16
  memory_gb: 32

# Directory structure configuration for building directories
directories:
  base_path: "./simulations"
  naming_pattern: "{system_name}_{window_num}_{optional}"
  subdirectories: # Any additional subdirectories that should be CREATED within each simulation window
    - "analysis"

# Simulation-specific configurations
simulations:

  em:
    subdirectory: "./simulations/em"
    name: "energy_minimization"
    min_method: 1
    MD_method: 0
    restart: False
    steps: 100000
    timestep: 0.004
    output_frequency: 50 # output control to be piped to amber

    nonbonded_cut: 10.0 # Angstrom
    
    restraint: True
    max_force: 10 #kcal/mol liable to change
    restraint_string: 
    - "a_Bb_CCC" # String that is liable to change
    - ':1-NUMRES@CA,C,N,O,PA,PB,Mg,MG'
    - ':1-NUMRES@CA,C,N,O,PA,PB,Mg,MG'

  NVT_ensemble: #NVT
    subdirectory: "./simulations/equil/NVT" #This is the subdirectory that will be created within each simulation window
    name: "NVT_Equilibration"
    MD_method: 0
    Force_calculation: 2
    PBC_treatment: 1 # NVT ensemble

    # TEMPERATURE CONTROL
    # ramped_heating: True # We can use the status of this flag to build subdirectories and file inputs
    # ramps: 5
    # initial_temperature: 0.0
    # final_temperature: 300.0

    ramped_heating: False
    ramps: 1 # Childers usually does multiple rounds of heating
    temperature: 300.0
    # initial_temperature: 0.0
    # final_temperature: 300.0

    thermostat: 1 # Multiple options here that map to different positional args
    Collision_frequency: 0.0
    heat_bath_coupling_constant: 1

    # simulation control
    steps: 100000 # steps per ramp
    timestep: 0.004 #ps
    hmass_repart: false
    nonbonded_cut: 10.0 
    output_frequency: 1000
    read_prev_coordinates: 1
    restart_sim: 1

    # RESTRAINTS 
    restraint: True
    restraint_weight: 25 
    max_force: 10 #kcal/mol 
    SHAKE_param: 2

    restraint_string: 
    - "a_Bb_CCC" # String that is liable to change
    # - ':1-NUMRES@CA,C,N,O,PA,PB,Mg,MG'
    # - ':1-NUMRES@CA,C,N,O,PA,PB,Mg,MG'
    # - ':1-NUMRES@CA,C,N,O,PA,PB,Mg,MG'
    # - ':1-NUMRES@CA,C,N,O,PA,PB,Mg,MG'
    # - ':1-NUMRES@CA,C,N,O,PA,PB,Mg,MG'
  NPT_ensemble:
    subdirectory: "./simulations/equil/NPT" # This is the subdirectory that will be created within each simulation window
    name: "NPT_Equilibration"
    
    pressure_control: 0 # 0=No pressure control, 1=Isotropic, 2=Anisotropic, 3=Semi-isotropic, 4=MD to target volume (REMD)
    barostat: 0

    MD_method: 0
    Force_calculation: 2
    PBC_treatment: 1 # NPT ensemble

    target_pressure: 1.0 # IN BAR
    pressure_scaling_factor: 1.0
    Anisotropy_Direction: 0

    restart_sim: False
    read_prev_coordinates: 0
    temperature: 310.0
    SHAKE_param: True

    steps: 1000000
    timestep: 0.004
    hmass_repart: false
    nonbonded_cut: 10.0
    output_frequency: 1000

    restraint: True
    max_force: 25 
    restraint_string: "a_Bb_CCC" # String that is liable to change

    
  production: #NVT production is common
    subdirectory: "./simulations/prod"
    name: "production"
    thermostat: 2

    steps: 5000000
    timestep: 0.004
    hmass_repart: false
    nonbonded_cut: 10.0
    output_frequency: 5000

    restraint: False
    restraint_weight: 0 
    restraint_string: ""


